(in-package #:cv)

;;; HighGUI
;;; NamedWindow
(define-export-constant +window-normal+ #x00000000)
(define-export-constant +window-autosize+ #x00000001)

;;; mouse-event
(define-export-constant +event-mouse-move+ 0)
(define-export-constant +event-l-button-down+ 1)
(define-export-constant +event-r-button-down+ 2)
(define-export-constant +event-m-button-down+ 3)
(define-export-constant +event-l-button-up+ 4)
(define-export-constant +event-r-button-up+ 5)
(define-export-constant +event-m-button-up+ 6)
(define-export-constant +event-l-button-dbl-clk+ 7)
(define-export-constant +event-r-button-dbl-clk+ 8)
(define-export-constant +event-m-button-dbl-clk+ 9)
(define-export-constant +event-mousewheel+ 10)
(define-export-constant +event-mouse-h-wheel+ 11)


(define-export-constant +event-flag-l-button+ 1)
(define-export-constant +event-flag-r-button+ 2)
(define-export-constant +event-flag-m-button+ 4)
(define-export-constant +event-flag-ctrl-key+ 8)
(define-export-constant +event-flag-shift-key+ 16)
(define-export-constant +event-flag-alt-key+ 32)

(define-export-constant +cap-prop-pos-msec+ 0)
(define-export-constant +cap-prop-pos-frame+ 1)
(define-export-constant +cap-prop-pos-avi-ratio+ 2)
(define-export-constant +cap-prop-frame-width+ 3)
(define-export-constant +cap-prop-frame-height+ 4)
(define-export-constant +cap-prop-fps+ 5)
(define-export-constant +cap-prop-fourcc+ 6)
(define-export-constant +cap-prop-frame-count+ 7)

(define-export-constant +cvtimg-flip+ 1)
(define-export-constant +cvtimg-swap-rb+ 2)


;;; font
(define-export-constant +font-hershey-simplex+ 0)
(define-export-constant +font-hershey-plain+ 1)
(define-export-constant +font-hershey-duplex+ 2)
(define-export-constant +font-hershey-complex+ 3)
(define-export-constant +font-hershey-triplex+ 4)
(define-export-constant +font-hershey-complex-small+ 5)
(define-export-constant +font-hershey-script-simplex+ 6)
(define-export-constant +font-hershey-script-complex+ 7)

;;; cvmat
(define-export-constant +8uc1+ 0)
(define-export-constant +8uc2+ 8)
(define-export-constant +8uc3+ 16)
(define-export-constant +8uc4+ 24)
(define-export-constant +8sc1+ 1)
(define-export-constant +8sc2+ 9)
(define-export-constant +8sc3+ 17)
(define-export-constant +8sc4+ 25)
(define-export-constant +16uc1+ 2)
(define-export-constant +16uc2+ 10)
(define-export-constant +16uc3+ 18)
(define-export-constant +16uc4+ 26)
(define-export-constant +16sc1+ 3)
(define-export-constant +16sc2+ 11)
(define-export-constant +16sc3+ 19)
(define-export-constant +16sc4+ 27)
(define-export-constant +32sc1+ 4)
(define-export-constant +32sc2+ 12)
(define-export-constant +32sc3+ 20)
(define-export-constant +32sc4+ 8)
(define-export-constant +32fc1+ 5)
(define-export-constant +32fc2+ 13)
(define-export-constant +32fc3+ 21)
(define-export-constant +32fc4+ 29)
(define-export-constant +64fc1+ 6)
(define-export-constant +64fc2+ 14)
(define-export-constant +64fc3+ 22)
(define-export-constant +64fc4+ 30)


;;; ipl image
;;; depth for createimage
(define-export-constant +ipl-depth-label+ 32)
(define-export-constant +ipl-depth-1u+ 1)
(define-export-constant +ipl-depth-8u+ 8)
(define-export-constant +ipl-depth-16u+ 16)
(define-export-constant +ipl-depth-32f+ 32)
(define-export-constant +ipl-depth-64f+ 64)
(define-export-constant +ipl-depth-8s+ -2147483640)
(define-export-constant +ipl-depth-16s+ -2147483632)
(define-export-constant +ipl-depth-32s+ -2147483616)


;;; dataorder
(define-export-constant +ipl-data-order-pixel+ 0)
(define-export-constant +ipl-data-order-plane+ 1)

;;; origin
(define-export-constant +ipl-origin-tl+ 0)
(define-export-constant +ipl-origin-bl+ 1)

;;; align
(define-export-constant +ipl-align-4bytes+ 4)
(define-export-constant +ipl-align-8bytes+ 8)
(define-export-constant +ipl-align-16bytes+ 16)
(define-export-constant +ipl-align-32bytes+ 32)

;;; histogram
(define-export-constant +hist-array+ 0)
(define-export-constant +hist-sparse+ 1)

(define-export-constant +comp-correl+ 0)
(define-export-constant +comp-chisqr+ 1)
(define-export-constant +comp-intersect+ 2)
(define-export-constant +comp-bhattacharyya+ 3)

;;; for cvloadimage
(define-export-constant +load-image-color+ 1)
(define-export-constant +load-image-grayscale+ 0)
(define-export-constant +load-image-unchanged+ -1)
(define-export-constant +load-image-anycolor+ 4)
(define-export-constant +load-image-anydepth+ 2)

;;; cvseq
(define-export-constant +seq-kind-generic+ 0)
(define-export-constant +seq-kind-curve+ 4096)
(define-export-constant +seq-kind-bin-tree+ 8192)
(define-export-constant +seq-kind-graph+ 4096)
(define-export-constant +seq-kind-subdiv2d+ 8192)
(define-export-constant +seq-flag-closed+ 16384)
(define-export-constant +seq-flag-simple+ 0)
(define-export-constant +seq-flag-convex+ 0)
(define-export-constant +seq-flag-hole+ 32768)

(define-export-constant +retr-external+ 0)
(define-export-constant +retr-list+ 1)
(define-export-constant +retr-ccomp+ 2)
(define-export-constant +retr-tree+ 3)


(define-export-constant +chain-code+ 0)
(define-export-constant +chain-approx-none+ 1)
(define-export-constant +chain-approx-simple+ 2)
(define-export-constant +chain-approx-tc89-l1+ 3)
(define-export-constant +chain-approx-tc89-kcos+ 4)
(define-export-constant +link-runs+ 5)

;;; cvTermCriteria
(define-export-constant +termcrit-iter+ 1)
(define-export-constant +termcrit-number+ +termcrit-iter+)
(define-export-constant +termcrit-eps+ 2)

;;; filter
(define-export-constant +covar-scrambled+ 0)
(define-export-constant +covar-normar+ 1)
(define-export-constant +covar-use-avg+ 2)
(define-export-constant +covar-scale+ 4)
(define-export-constant +covar-rows+ 8)
(define-export-constant +covar-cols+ 16)

(define-export-constant +cmp-eq+ 0)
(define-export-constant +cmp-gt+ 1)
(define-export-constant +cmp-ge+ 2)
(define-export-constant +cmp-lt+ 3)
(define-export-constant +cmp-le+ 4)
(define-export-constant +cmp-ne+ 5)

(define-export-constant +lu+ 0)
(define-export-constant +svd+ 1)
(define-export-constant +svd-sym+ 2)
(define-export-constant +cholesky+ 3)
(define-export-constant +qr+ 4)
(define-export-constant +normal+ 16)

(define-export-constant +c+ 1)
(define-export-constant +l1+ 2)
(define-export-constant +l2+ 4)
(define-export-constant +norm-mask+ 7)
(define-export-constant +relative+ 8)
(define-export-constant +diff+ 16)
(define-export-constant +minmax+ 32)
(define-export-constant +diff-c+ 17)
(define-export-constant +diff-l1+ 18)
(define-export-constant +diff-l2+ 20)
(define-export-constant +relative-c+ 9)
(define-export-constant +relative-l1+ 10)
(define-export-constant +relative-l2+ 12)

(define-export-constant +reduce-sum+ 0)
(define-export-constant +reduce-avg+ 1)
(define-export-constant +reduce-max+ 2)
(define-export-constant +reduce-min+ 3)

(define-export-constant +svd-modify-a+ 1)
(define-export-constant +svd-u-t+ 2)
(define-export-constant +svd-v-t+ 4)

(define-export-constant +bgr-2-bgra+ 0)
(define-export-constant +rgb-2-rgba+ 0)
(define-export-constant +bgra-2-bgr+ 1)
(define-export-constant +rgba-2-rgb+ 1)
(define-export-constant +bgr-2-rgba+ 2)
(define-export-constant +rgb-2-bgra+ 2)
(define-export-constant +rgba-2-bgr+ 3)
(define-export-constant +bgra-2-rgb+ 3)
(define-export-constant +bgr-2-rgb+ 4)
(define-export-constant +rgb-2-bgr+ 4)
(define-export-constant +bgra-2-rgba+ 5)
(define-export-constant +rgba-2-bgra+ 5)
(define-export-constant +bgr-2-gray+ 6)
(define-export-constant +rgb-2-gray+ 7)
(define-export-constant +gray-2-bgr+ 8)
(define-export-constant +gray-2-rgb+ 8)
(define-export-constant +gray-2-bgra+ 9)
(define-export-constant +gray-2-rgba+ 9)
(define-export-constant +bgra-2-gray+ 10)
(define-export-constant +rgba-2-gray+ 11)
(define-export-constant +bgr-2-bgr565+ 12)
(define-export-constant +bgr565-2-bgr+ 14)
(define-export-constant +bgra-2-bgr565+ 16)
(define-export-constant +bgr565-2-bgra+ 18)
(define-export-constant +gray-2-bgr565+ 20)
(define-export-constant +bgr565-2-gray+ 21)
(define-export-constant +bgr-2-bgr555+ 22)
(define-export-constant +bgr555-2-bgr+ 24)
(define-export-constant +bgra-2-bgr555+ 26)
(define-export-constant +bgr555-2-bgra+ 28)
(define-export-constant +gray-2-bgr555+ 30)
(define-export-constant +bgr555-2-gray+ 31)
(define-export-constant +bgr-2-xyz+ 32)
(define-export-constant +xyz-2-bgr+ 34)
(define-export-constant +bgr-2-ycrcb+ 36)
(define-export-constant +ycrcb-2-bgr+ 38)
(define-export-constant +bgr-2-hsv+ 40)
(define-export-constant +bgr-2-lab+ 44)
(define-export-constant +bayerbg-2-bgr+ 46)
(define-export-constant +bayergb-2-bgr+ 47)
(define-export-constant +bayerrg-2-bgr+ 48)
(define-export-constant +bayergr-2-bgr+ 49)
(define-export-constant +bgr-2-luv+ 50)
(define-export-constant +bgr-2-hls+ 52)
(define-export-constant +hsv-2-bgr+ 54)
(define-export-constant +lab-2-bgr+ 56)
(define-export-constant +luv-2-bgr+ 58)
(define-export-constant +hls-2-bgr+ 60)

(define-export-constant +blur-no-scale+ 0)
(define-export-constant +blur+ 1)
(define-export-constant +gaussian+ 2)
(define-export-constant +median+ 3)
(define-export-constant +bilateral+ 4)

(define-export-constant +shape-rect+ 0)
(define-export-constant +shape-cross+ 1)
(define-export-constant +shape-ellipse+ 2)
(define-export-constant +shape-custom+ 100)

(define-export-constant +mop-erode+ 0)
(define-export-constant +mop-dilate+ 1)
(define-export-constant +mop-open+ 2)
(define-export-constant +mop-close+ 3)
(define-export-constant +mop-gradient+ 4)
(define-export-constant +mop-tophat+ 5)
(define-export-constant +mop-blackhat+ 6)

(define-export-constant +flood-fill-fixed-range+ 65536)
(define-export-constant +flood-fill-mask-only+ 131072)

(define-export-constant +inter-nn+ 0)
(define-export-constant +inter-linear+ 1)
(define-export-constant +inter-cubic+ 2)
(define-export-constant +inter-area+ 3)
(define-export-constant +inter-lanczos4+ 4)

(define-export-constant +gaussian-5x5+ 7)

(define-export-constant +thresh-binary+ 0)
(define-export-constant +thresh-binary-inv+ 1)
(define-export-constant +thresh-trunc+ 2)
(define-export-constant +thresh-tozero+ 3)
(define-export-constant +thresh-tozero-inv+ 4)
(define-export-constant +thresh-mask+ 7)
(define-export-constant +thresh-otsu+ 8)

(define-export-constant +adaptive-thresh-mean-c+ 0)
(define-export-constant +adaptive-thresh-gaussian-c+ 1)

(define-export-constant +ipl-border-constant+ 0)
(define-export-constant +ipl-border-replicate+ 1)

(define-export-constant +inter-nn+ 0)
(define-export-constant +inter-linear+ 1)
(define-export-constant +inter-cubic+ 2)
(define-export-constant +inter-area+ 3)
(define-export-constant +inter-lanczos4+ 4)

(define-export-constant +warp-fill-outliers+ 8)
(define-export-constant +warp-inverse-map+ 16)

(define-export-constant +dxt-forward+ 0)
(define-export-constant +dxt-inverse+ 1)
(define-export-constant +dxt-scale+ 2)
(define-export-constant +dxt-inv-scale+ 3)
(define-export-constant +dxt-inverse-scale+ 3)
(define-export-constant +dxt-rows+ 4)
(define-export-constant +dxt-mul-conj+ 8)

(define-export-constant +dist-user+ -1)
(define-export-constant +dist-l1+ 1)
(define-export-constant +dist-l2+ 2)
(define-export-constant +dist-c+ 3)
(define-export-constant +dist-l12+ 4)
(define-export-constant +dist-fair+ 5)
(define-export-constant +dist-welsch+ 6)
(define-export-constant +dist-huber+ 7)

(define-export-constant +dist-label-ccomp+ 0)
(define-export-constant +dist-label-pixel+ 1)

(define-export-constant +tm-sqdiff+ 0)
(define-export-constant +tm-sqdiff-normed+ 1)
(define-export-constant +tm-ccorr+ 2)
(define-export-constant +tm-ccorr-normed+ 3)
(define-export-constant +tm-ccoeff+ 4)
(define-export-constant +tm-ccoeff-normed+ 5)

(define-export-constant +contours-match-i1+ 1)
(define-export-constant +contours-match-i2+ 2)
(define-export-constant +contours-match-i3+ 3)

(define-export-constant +clockwise+ 1)
(define-export-constant +counter-clockwise+ 2)

(define-export-constant +haar-do-canny-pruning+ 1)
(define-export-constant +haar-scale-image+ 2)
(define-export-constant +haar-find-biggest-object+ 4)
(define-export-constant +haar-do-rough-search+ 8)

